name: lint OAS3 description documents with Spectral

on:
  push:
    paths:
      - ./examples/**/*.yaml
      - .github/workflows/lint-oas3.yml
      - .spectral.yaml
  workflow_dispatch:

jobs:
  spectral-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run spectral:oas:lint